'use client'

import { Download } from 'lucide-react'

export default function DownloadPDFButton({ title, content }: { title: string; content: string }) {
  const handleDownload = () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              color: #111;
              max-width: 800px;
              margin: 40px auto;
              padding: 0 20px;
            }
            h1, h2, h3 {
              color: #4f46e5;
              border-bottom: 2px solid #e5e7eb;
              padding-bottom: 8px;
              margin-top: 24px;
            }
            p, li {
              font-size: 14px;
              color: #374151;
            }
            ul, ol {
              padding-left: 20px;
            }
            .footer {
              margin-top: 50px;
              font-size: 12px;
              color: #9ca3af;
              text-align: center;
              border-top: 1px solid #e5e7eb;
              padding-top: 10px;
            }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <p><em>Generated by LearnSphere AI Study Companion</em></p>
          <hr />
          <div>
            ${content.replace(/\n/g, '<br />')}
          </div>
          <div class="footer">
            <p>© LearnSphere AI — Personalized Learning Platform</p>
          </div>
          <script>
            window.onload = function() {
              window.print();
            }
          </script>
        </body>
      </html>
    `

    printWindow.document.write(htmlContent)
    printWindow.document.close()
  }

  return (
    <button
      onClick={handleDownload}
      className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-2 rounded-xl text-xs font-semibold shadow-lg shadow-indigo-600/20 transition-all"
    >
      <Download className="w-4 h-4" /> Download PDF / Print
    </button>
  )
}
